routes/web.php
<?php

use \Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('alerts', 'AlertsController');
Route::resource('locations', 'LocationsController');
Route::resource('files', 'FilesController');
Route::resource('cameras', 'CamerasController');

app/Locations.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Locations extends Model
{
    protected $table = 'locations';
    protected $fillable = [
        'name',
        'user_id'
    ];
}

app/Http/Controllers/LocationsController.php
<?php

namespace App\Http\Controllers;

use App\Locations;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class LocationsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Factory|View
     */
    public function index(Request $request)
    {
        $query = Locations::query();
        $query = $this->queryFilter($request, $query);
        $table = $query->paginate(15);
        return view('models.locations.index')
            ->with('table', $table);
    }

    protected function queryFilter(Request $request, Builder $query): Builder
    {
        $query->where('user_id', '=', Auth::user()->id);

        return $query;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return Factory|View
     */
    public function create(Request $request)
    {
        return view('models.locations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|Redirector
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $input = array_merge($input, ['user_id' => Auth::user()->id]);

        Locations::create($input);

        return redirect(route('locations.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param Request $request
     * @param Locations $locations
     * @return Factory|View
     */
    public function show(Request $request, $locations)
    {
        $findResult = Locations::find($locations);

        if (empty($findResult)) {
            return redirect(route('locations.index'));
        }
        return view('models.locations.show')
            ->with('object', $findResult);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Request $request
     * @param Locations $locations
     * @return \Illuminate\Http\RedirectResponse|Redirector
     */
    public function edit(Request $request, $locations)
    {
        $findResult = Locations::find($locations);

        if (empty($findResult)) {
            return redirect(route('locations.index'));

        }

        return view('models.locations.edit')
            ->with('object', $findResult);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Locations $locations
     * @return Response
     */
    public function update(Request $request, $locations)
    {
        $objToUpdate = Locations::find($locations);

        if (empty($objToUpdate)) {
            return redirect(route('locations.index'));
        }

        $input = $request->all();

        $objToUpdate->update($input);

        return redirect(route('locations.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param Locations $locations
     * @return void
     */
    public function destroy(Request $request, $locations)
    {
        $findResult = Locations::find($locations);

        if (empty($findResult)) {
            return redirect(route('locations.index'));
        }

        Locations::destroy($findResult->id);

        return redirect(route('locations.index'));
    }
}

resources/views/models/locations/create.blade.php
@extends('adminlte::page')

@section('content')

<div class="Container">
    <div class="card col-5">
        <div class="card-header fz-20">
          Agregar Locación
        </div>
        <div class="box box-primary">
            <div class="box-body">
                <div>
                    {!! Form::open(['route' => 'cameras.store']) !!}

                    @include('models.cameras.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
      </div>
    </div>

@endsection

resources/views/models/locations/edit.blade.php
@extends('adminlte::page')

@section('content')

    <section class="content-header">
        <h1 class="pull-left">Locations Edit</h1>
    </section>

    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::model($object, ['route' => ['locations.update', $object->id], 'method' => 'patch']) !!}

                    @include('models.locations.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/models/locations/fields.blade.php
<div class="form-group col-12">
    {!! Form::label('name', 'Nombre:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

{{--<div class="form-group col-12">--}}
{{--    {!! Form::label('user_id', 'Usuario:') !!}--}}
{{--    {!! Form::text('user_id', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Submit Field -->
<div class="form-group text-center col-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('locations.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/models/locations/index.blade.php
@extends('adminlte::page')

@section('content')

    <section class="content-header">
        <h1 class="pull-left ">Locaciones</h1>
    </section>

    <div class="container p-0">
        <div class="row">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane bg-white fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <table class="table table-striped">
                        <thead>
                        <tr class="tab-header">
                            <th scope="col text-uppercase">ID</th>
                            <th scope="col text-uppercase">Name</th>
                            <th scope="col text-uppercase">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(isset($table))
                            @foreach($table as $row)
                                <tr>
                                    <td>{{ $row->id }}</td>
                                    <td>{{ $row->name }}</td>
                                    <td>
                                        {!! Form::open(['route' => ['cameras.destroy', $row], 'method' => 'delete']) !!}
                                        <div class='btn-group'>
{{--                                            <a href="{!! route('cameras.show', [$row]) !!}"--}}
{{--                                               class='btn btn-default btn-xs'>--}}
{{--                                                <i class="far fa-eye"></i>--}}
{{--                                            </a>--}}
{{--                                            <a href="{!! route('cameras.edit', [$row]) !!}"--}}
{{--                                               class='btn btn-default btn-xs'>--}}
{{--                                                <i class="fas fa-edit"></i>--}}
{{--                                            </a>--}}
                                            {!! Form::button('<i class="glyphicon glyphicon-trash"></i>',
                                            ['type' => 'submit', 'class' => 'fas fa-trash-alt btn-delete',
                                             'onclick' => "return confirm('Are you sure?')"]) !!}
                                        </div>
                                        {!! Form::close() !!}

                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div>
            <div class="pagination-btns text-center">
            {{ $table->links() }}
            </div>
        </div>

        <section class="col-12 text-right">


            <h1 class="">
                <a class="btn btn-primary " style="margin-top: -10px;margin-bottom: 5px"
                   href="#popupLocations">Agregar Locación</a>
            </h1>

        </section>

        <div id="popupLocations" class="overlay">

            <div class="card col-5 popupLocationsBody">
                <div class="card-header fz-20">
                    Agregar Locación
                </div>
                <div class="box box-primary">
                    <div class="box-body">
                        <div>
                            {!! Form::open(['route' => 'locations.store']) !!}

                            @include('models.locations.fields')

                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/models/locations/show.blade.php
@extends('adminlte::page')

@section('content')

    <section class="content-header">
        <h1 class="pull-left">Locations Show</h1>
    </section>



@endsection